[pgagroal]
host = localhost
port = 2345

log_type = file
log_level = info
log_path = /home/myuser/pgagroal/test_env/log/pgagroal1.log
metrics = 3000
health_check = on
health_check_period = 30
health_check_timeout = 5
health_check_user = postgres

max_connections = 100
idle_timeout = 600
validation = off
unix_socket_dir = /home/myuser/pgagroal/test_env/run
ev_backend = auto

[primary]
host = localhost
port = 5432
