[pgagroal-vault]
host = localhost
port = 2500
metrics = 3000
log_type = console
log_level = trace
log_path = /home/user1995/pgagroal/build/src/vault.log
ev_backend= io_uring
tls = off
tls_cert_file = /home/base/tls/pgagroal.crt
tls_key_file = /home/base/tls/pgagroal.key
# tls_ca_file = /home/base/tls/pgagroal.crt


# metrics_cert_file=/home/base/tls/pgagroal.crt
# metrics_key_file=/home/base/tls/pgagroal.key
# metrics_ca_file=/home/base/tls/pgagroal.crt

[main]
host = localhost
port = 2346
user = admin
