name: Build Hindi Documentation

on:
  push:
    branches:
      - translate2
  pull_request:
    branches:
      - translate2
  workflow_dispatch:

jobs:
  build-hindi-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and start LibreTranslate in background
        run: |
          pip install libretranslate
          nohup libretranslate > libretranslate.log 2>&1 &
          # Wait up to 10 minutes for LibreTranslate to be ready
          for i in {1..120}; do
            if curl -s -X POST http://localhost:5000/translate -d q="Hello" -d source=en -d target=es | grep -q '"translatedText"'; then
              echo "LibreTranslate is ready"
              break
            fi
            echo "Waiting for LibreTranslate to be ready... ($i/120)"
            sleep 5
          done

      - name: Test LibreTranslate
        run: |
          curl -X POST http://localhost:5000/translate -d q="Hello" -d source=en -d target=es

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Translate Markdown files to Hindi
        run: |
          #!/bin/bash
          set -e
          TRANSLATE_URL="http://localhost:5000/translate"
          SRC_DIR="doc"
          DST_DIR="document_hindi"
          TIMEOUT=300

          echo "Current working directory: $(pwd)"

          # Copy the entire doc directory to document_hindi
          if [ -d "$DST_DIR" ]; then
            echo "Removing existing $DST_DIR directory..."
            rm -rf "$DST_DIR"
          fi

          echo "Copying $SRC_DIR to $DST_DIR..."
          cp -r "$SRC_DIR" "$DST_DIR"

          find "$DST_DIR" -type f -name "*.md" | while read -r file; do
            echo "Translating: $file"
            content=$(cat "$file")
            # Escape content for JSON
            json=$(jq -n --arg q "$content" --arg source "en" --arg target "hi" '{q: $q, source: $source, target: $target}')
            response=$(timeout $TIMEOUT curl -s -X POST -H "Content-Type: application/json" -d "$json" "$TRANSLATE_URL" || echo "__TIMEOUT__")
            if [ "$response" = "__TIMEOUT__" ]; then
              echo "ERROR: Timeout translating $file"
              continue
            fi
            # Try to extract translated text
            translated=$(echo "$response" | jq -r '.translatedText // empty')
            if [ -z "$translated" ]; then
              echo "ERROR: Translation failed for $file"
              continue
            fi
            echo "$translated" > "$file"
            echo "Saved translated file: $file"
          done

          echo "Translation complete. All translated files are in $DST_DIR"

      - name: Upload Hindi docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hindi-docs
          path: document_hindi/
